### ISSUE TITLE
ttrv keeps crashing on Mac OS Catalina 

### ISSUE THREAD

**Issue by ashutoshmjain** [tildeclub/ttrv#25]
**Describe the bug**
A clear description of what the bug is and how to reproduce it.

**Describe your environment**
- If a stack trace was displayed on the command line, paste the entire output here.
- Otherwise, run ``$rtv --debug-info`` and paste the entire output here.
- Include any other information that might be relevant to the issue (For example, your operating system, your terminal emulator, how you installed rtv, etc.)

ttrv version: ttrv 1.27.2
ttrv module path: /Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/__main__.py
python version: 3.9.0 (default, Nov 13 2020, 18:01:38)  [Clang 12.0.0 (clang-1200.0.31.1)]
python executable: /Users/ashutosh/.pyenv/versions/3.9.0/bin/python3.9
praw version: packaged, commit 1656ec224e57
locale, encoding: C/UTF-8/C/C/C/C, UTF-8
Environment Variables
  BROWSER         :
  DISPLAY         :
  EDITOR          :
  LANG            :
  PAGER           :
  TTRV_BROWSER    :
  TTRV_EDITOR     :
  TTRV_PAGER      :
  TTRV_URLVIEWER  :
  TERM            : xterm-256color
  VISUAL          :
  XDG_CONFIG_HOME :
  XDG_DATA_HOME   :

Traceback (most recent call last):
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/__main__.py", line 255, in main
    page = page.loop()
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/page.py", line 94, in loop
    self.controller.trigger(ch)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/objects.py", line 604, in trigger
    return func(self.instance, *args, **kwargs)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/page.py", line 319, in login
    self.oauth.authorize()
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/oauth.py", line 190, in authorize
    self.term.open_browser(authorize_url)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ttrv/terminal.py", line 618, in open_browser
    p.start()
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/ashutosh/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'

ttrv has crashed. Please report this traceback at:
https://github.com/tildeclub/ttrv/issues

**Comment by ashutoshmjain** [comment]
it crashes when I press u to log in after first run post install. . Same behaviour with itv and tuir as well. I thought its a Python issue on Mac OS Catalina , so installed latest version of Python with pyenv ..

**Comment by deepend-tildeclub** [comment]
> it crashes when I press u to log in after first run post install. . Same behaviour with itv and tuir as well. I thought its a Python issue on Mac OS Catalina , so installed latest version of Python with pyenv ..

what version of python was being used previous to you updating python?

**Comment by nanocortex** [comment]
Same thing on macOS Big Sur. I think it's related to: https://github.com/tildeclub/ttrv/issues/25

**Comment by Saul-Dickson** [comment]
I'm using 3.9 and having the same issue, right down to the traceback.
``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ttrv/__main__.py", line 255, in main
    page = page.loop()
  File "/usr/local/lib/python3.9/site-packages/ttrv/page.py", line 94, in loop
    self.controller.trigger(ch)
  File "/usr/local/lib/python3.9/site-packages/ttrv/objects.py", line 604, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ttrv/page.py", line 319, in login
    self.oauth.authorize()
  File "/usr/local/lib/python3.9/site-packages/ttrv/oauth.py", line 190, in authorize
    self.term.open_browser(authorize_url)
  File "/usr/local/lib/python3.9/site-packages/ttrv/terminal.py", line 618, in open_browser
    p.start()
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'
```

**Comment by nanocortex** [comment]
I managed to resolve that issue by building from source and making sure I'm using latest python 3.9 from Homebrew (not MacOS default).

**Comment by dcontiveros** [comment]
Managed to track down the problem. The issue, as highlighted by @nanocortex is that the ttrv module version installed by pip is version 1.27.2:

`$ cat __version__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

__version__ = '1.27.2'`

When you pull this via pip, the forking code in Terminal.py module is prior to this merge:

https://github.com/tildeclub/ttrv/pull/21/commits/4f555fb3ed372654566f3c2c156df47307a3774d

Installing from source is the way to go here, which is accomplished by the following commands:

`
git clone https://github.com/tildeclub/ttrv.git
cd ttrv
python setup.py install --user --prefix=
`

**Comment by deepend-tildeclub** [comment]
updated the PyPi repo. Version on github and pypi now match.

**Comment by nanocortex** [comment]
Reinstalled with `pip install ttrv` and now it works as intended. Thank you!

**Comment by ashutoshmjain** [comment]
Thanks guys .. really appreciate.
