### ISSUE TITLE
New crashes on OS X Mojave

### ISSUE THREAD

**Issue by apexatoll** [tildeclub/ttrv#28]
Hi,

I am having some issues with ttrv, everything was working fine until a couple of days ago seemingly after a brew update. I think it involved an update to python but I'm not 100% sure as I have rolled back my brew history and the problem still persists.  I am running OS X Mojave 10.14.6 and Python 3.9.0

Trying to open ttrv results in the following traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ttrv", line 33, in <module>
    sys.exit(load_entry_point('ttrv==1.27.2', 'console_scripts', 'ttrv')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ttrv", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttrv-1.27.2-py3.9.egg/ttrv/__main__.py", line 280, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttrv-1.27.2-py3.9.egg/ttrv/__main__.py", line 144, in main
    patch_webbrowser()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttrv-1.27.2-py3.9.egg/ttrv/objects.py", line 56, in patch_webbrowser
    webbrowser.register('surf', None, webbrowser.BackgroundBrowser('surf'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttrv-1.27.2-py3.9.egg/ttrv/objects.py", line 49, in register_patch
    return webbrowser._register(name, klass, instance, preferred=preferred)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/webbrowser.py", line 26, in register
    register_standard_browsers()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/webbrowser.py", line 551, in register_standard_browsers
    raw_result = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'xdg-settings'
```

My environment variable $DISPLAY is set to "1"  as this meant I could view post attachments in mpv and this worked fine. However setting $DISPLAY to an empty string allows ttrv to open with no issues but means that I can no longer view post media so is not ideal. I have tried reinstalling ttrv through pip and also from source

I would greatly appreciate any advice, thanks in advance!

**Comment by apexatoll** [comment]
I fixed the issue, it seems to be some problem with how python assigns default browsers. If anyone else runs into this problem I fixed this by changing line 548 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/webbrowser.py
From 
`if os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"):`
To
`if os.environ.get("WAYLAND_DISPLAY"):`
