### ISSUE TITLE
wl-copy needed for Wayland clipboard

### ISSUE THREAD

**Issue by gbpi** [tildeclub/ttrv#32]
I've been trying out Wayland lately and using wl-copy works fine in place of xsel or xclip. I hacked it in by replacing xsel in clipboard.py. It doesn't seem to require arguments, but I didn't look too deeply into it yet.

Maybe make the command user configurable?

**Comment by omarys** [comment]
I made a fork of RTV that changed that section of code, but I'm looking at adding functions to do both.  I've never done anything with Python before, so it's probably not correct.  I can't test it because I'm getting errors for version:

Traceback (most recent call last):
  File "/run/media/omary/0D81-2B3D/Code/ttrv/setup.py", line 5, in <module>
    from version import __version__ as version
  File "/run/media/omary/0D81-2B3D/Code/ttrv/version.py", line 1, in <module>
    ttrv/__version__.py

My untested code looks like this:

def copy_linux(text):

    def get_xserver_commands():
        for cmd in ['xsel', 'xclip']:
            cmd_exists = subprocess.call(
                ['which', cmd],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
            if cmd_exists:
                return cmd
            else:
                return None

    def get_wayland_commands():
        for cmd in ['wl-copy', 'wl-paste']:
            cmd_exists = subprocess.call(
                ['which', cmd],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
            if cmd_exists:
                return cmd
            else:
                return None

    xserver_cmd = get_xserver_commands()
    wayland_cmd = get_wayland_commands()

    if xserver_cmd is not None:
        cmd_args = {
            'xsel': ['xsel', '-b', '-i'],
            'xclip': ['xclip', '-selection', 'c']}
        cmd_name = xserver_cmd
    elif wayland_cmd is not None:
        cmd_args = {
            'wl-copy': ['wl-copy', '-p'],
            'wl-paste': ['wl-paste', '-p']}
        cmd_name = wayland_cmd
    else:
        raise ProgramError("External copy application not found")

    _subprocess_copy(text, cmd_args.get(cmd_name))
