### ISSUE TITLE
crash when unbinding "J" from "SUBMISSION_GOTO_SIBLING"

### ISSUE THREAD

**Issue by lacygoill** [tildeclub/ttrv#40]
**Describe the bug**

`ttrv(1)` crashes when we unbind `J` from the `SUBMISSION_GOTO_SIBLING` command.

That is, in `$XDG_CONFIG_HOME/ttrv/ttrv.cfg`, write this:

    [bindings]
    SUBMISSION_GOTO_SIBLING = x

`x` does not matter.  But notice that now, `J` is no longer bound to `SUBMISSION_GOTO_SIBLING`.

Start the program, visit a subreddit, open a submission, and press `J`:  `ttrv(1)` crashes.

**Describe your environment**

- Stack trace:

      ttrv version: ttrv 1.27.3
      ttrv module path: /home/lgc/.local/lib/python3.8/site-packages/ttrv/__main__.py
      python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
      python executable: /usr/bin/python3
      praw version: packaged, commit 1656ec224e57
      locale, encoding: en_US.UTF-8, UTF-8
      Environment Variables
        BROWSER         : firefox
        DISPLAY         : :0.0
        EDITOR          : vim
        LANG            : en_US.UTF-8
        PAGER           : less
        TTRV_BROWSER    :
        TTRV_EDITOR     :
        TTRV_PAGER      :
        TTRV_URLVIEWER  : urlscan
        TERM            : tmux-256color
        VISUAL          : vim
        XDG_CONFIG_HOME : /home/lgc/.config
        XDG_DATA_HOME   : /home/lgc/.local/share

      Traceback (most recent call last):
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/__main__.py", line 255, in main
          page = page.loop()
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/page.py", line 97, in loop
          self.handle_selected_page()
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/subreddit_page.py", line 43, in handle_selected_page
          self.selected_page = self.selected_page.loop()
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/page.py", line 94, in loop
          self.controller.trigger(ch)
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/objects.py", line 604, in trigger
          return func(self.instance, *args, **kwargs)
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/page.py", line 214, in move_next_unread
          self._move_cursor_to_unread(1)
        File "/home/lgc/.local/lib/python3.8/site-packages/ttrv/page.py", line 891, in _move_cursor_to_unread
          url_in_history = data['url_full'] in self.config.history
      KeyError: 'url_full'

      ttrv has crashed. Please report this traceback at:
      https://github.com/tildeclub/ttrv/issues

- Output from `$ttrv --debug-info`:

      $ ttrv --debug-info
      ttrv version: ttrv 1.27.3
      ttrv module path: /home/lgc/.local/lib/python3.8/site-packages/ttrv/__main__.py
      python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
      python executable: /usr/bin/python3
      praw version: packaged, commit 1656ec224e57
      locale, encoding: en_US.UTF-8, UTF-8
      Environment Variables
        BROWSER         : firefox
        DISPLAY         : :0.0
        EDITOR          : vim
        LANG            : en_US.UTF-8
        PAGER           : less
        TTRV_BROWSER    :
        TTRV_EDITOR     :
        TTRV_PAGER      :
        TTRV_URLVIEWER  : urlscan
        TERM            : tmux-256color
        VISUAL          : vim
        XDG_CONFIG_HOME : /home/lgc/.config
        XDG_DATA_HOME   : /home/lgc/.local/share

- OS: Ubuntu 20.04.2 LTS
- Terminal: XTerm(353)
- `ttrv(1)` was installed with:

      python3 -m pip install --user --upgrade ttrv

---

Same issue when we unbind `K` from `SUBMISSION_GOTO_PARENT`, then later press `K`.

---

Not sure this is the correct fix, but I *think* this patch would fix the issue:

```diff
diff --git a/ttrv/page.py b/ttrv/page.py
index 743de8c..733e8c8 100644
--- a/ttrv/page.py
+++ b/ttrv/page.py
@@ -888,7 +888,7 @@ class Page(object):
             valid, redraw = self.nav.move(direction, len(self._subwindows))
             if valid:
                 data = self.get_selected_item()
-                url_in_history = data['url_full'] in self.config.history
+                url_in_history = data.get('url_full') in self.config.history
         if not valid:
             self.term.flash()
 
```

**Comment by lacygoill** [comment]
Unrelated but the mailcap template might be slightly improved.  Currently, it runs `mpv(1)` like this:

    mpv -vo drm -quiet '%s'

But with this command, a recent `mpv(1)` (0.32.0) gives the following warning:

   > The legacy option syntax ('-vo value') is deprecated and dangerous.
   > Please use '--vo=value'.

It can be suppressed by changing the command like this:

    mpv --vo=drm -quiet '%s'

As a suggestion, here is a patch:
```diff
diff --git a/ttrv/templates/mailcap b/ttrv/templates/mailcap
index 7540b3c..0ade11d 100644
--- a/ttrv/templates/mailcap
+++ b/ttrv/templates/mailcap
@@ -62,8 +62,8 @@ image/*; curl -s '%s' | convert -resize 80x80 - jpg:/tmp/ttrv.jpg && img2xterm /
 image/*; curl -s '%s' | convert - jpg:/tmp/ttrv.jpg && img2txt -f utf8 /tmp/ttrv.jpg; needsterminal; copiousoutput
 
 # Full motion videos - requires a framebuffer to view
-video/x-youtube; mpv -vo drm -quiet '%s'; needsterminal
-video/*; mpv -vo drm -quiet '%s'; needsterminal
+video/x-youtube; mpv --vo=drm -quiet '%s'; needsterminal
+video/*; mpv --vo=drm -quiet '%s'; needsterminal
 
 # Ascii videos
 # video/x-youtube; youtube-dl -q -o - '%s' | mplayer -cache 8192 -vo caca -quiet -; needsterminal
```
