### ISSUE TITLE
Crash when trying to open any link on browser.

### ISSUE THREAD

**Issue by jspanos** [tildeclub/ttrv#5]
On macOS Catalina with python 3.8, every time I am trying to interact with links that need a browser to open ttrv is crashing.

The crash log is the following:

`ttrv version: ttrv 1.27.0
ttrv module path: /private/tmp/ttrv/ttrv/__main__.py
python version: 3.8.2 (default, Mar 11 2020, 00:29:50)  [Clang 11.0.0 (clang-1100.0.33.17)]
python executable: /usr/local/opt/python@3.8/bin/python3.8
praw version: packaged, commit 1656ec224e57
locale, encoding: en_US.UTF-8, UTF-8
Environment Variables
  BROWSER         :
  DISPLAY         :
  EDITOR          :
  LANG            : en_US.UTF-8
  PAGER           : less
  TTRV_BROWSER    :
  TTRV_EDITOR     :
  TTRV_PAGER      :
  TTRV_URLVIEWER  :
  TERM            : screen-256color
  VISUAL          :
  XDG_CONFIG_HOME :
  XDG_DATA_HOME   :

Traceback (most recent call last):
  File "/private/tmp/ttrv/ttrv/__main__.py", line 255, in main
    page = page.loop()
  File "/private/tmp/ttrv/ttrv/page.py", line 94, in loop
    self.controller.trigger(ch)
  File "/private/tmp/ttrv/ttrv/objects.py", line 604, in trigger
    return func(self.instance, *args, **kwargs)
  File "/private/tmp/ttrv/ttrv/subreddit_page.py", line 185, in open_link
    self.term.open_link(data['url_full'])
  File "/private/tmp/ttrv/ttrv/terminal.py", line 453, in open_link
    self.open_browser(url)
  File "/private/tmp/ttrv/ttrv/terminal.py", line 615, in open_browser
    p.start()
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'
`
This is a known bug under rtv repo, here is some open issues that describe the same bug
https://github.com/michael-lazar/rtv/search?q=AttributeError%3A+Can%27t+pickle+local+object&type=Issues

I am currently working on a fix, I ll open a PR as soon as possible.

**Comment by jspanos** [comment]
Here it is https://github.com/tildeclub/ttrv/pull/6

**Comment by deepend-tildeclub** [comment]
Thanks
